# Dividi and Conquer - Bo'lib tashlab hukmronlik qil
#
#
#      Dividi & Conquer
#  * Ba'zida muammolarga yechim ko'rinmaydi.
#  * Yaxshi dasturchi muammo oldida yengilmaydi.
#  * Katta muammoni mayda muammoga bo'lib olib,
#     har bir muammoni alohida hal qiladi.
#  * Bu Dividi and Conquer metodi deb ataladi.
#  * Dividi and Conquer metodi juda ko'p muammolarga
#     yechim bo'lishi mumkin.
#  * Keyingi safar shu muammoga duch kelganingizda shu 
#     metodni esga soling.
#
#
#